version: '2'
services:
  web:
    image: jorgeandrada/syspass-recovery:develop
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config.xml:/root/config.xml:ro

  syspass:
    restart: always
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      - MYSQL_USER=sp_admin
      - MYSQL_PASSWORD=PaSsword12345_23
      - MYSQL_DATABASE=syspass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
